### ISSUE TITLE
Including colors.css, not only variables ?

### ISSUE THREAD

**Issue by voronianski** [jxnblk/basscss-color-base#1]
Maybe it's worth to include the whole `colors.css` here - https://github.com/jxnblk/basscss-color-base/blob/master/index.css#L3 as ``@import 'colors.css/myth/colors';`` ?

Or mention in docs that it's necessary to include colors.css as well - http://www.basscss.com/docs/color/#color-base

**Comment by jxnblk** [comment]
`basscss-color-base` only uses the variables from `colors.css` because of a discrepancy in naming conventions for border colors. `basscss-colors` is where all the color, background-color, and border-color styles are declared. https://github.com/jxnblk/basscss-colors/blob/master/index.css
